name: Publish Release

on:
  push:
    tags:
      - 'v*' # Triggers only when pushing a tag starting with 'v'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: NeonCharacterBuilder
            ext: exe

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: 'maven' # Automatically caches Maven dependencies to speed up future runs

    - name: Build with Maven
      run: mvn -B clean compile assembly:single --file pom.xml

    - name: Run jpackage (Windows)
      run: jpackage --type app-image --name NeonCharacterBuilder --input target --main-jar NeonCharacterBuilder.jar --main-class ncb.main.BaseCharacterWindow --dest target

    - name: Zip up the App Image
      shell: powershell
      run: Compress-Archive -Path target/NeonCharacterBuilder -DestinationPath target/NeonCharacterBuilder-Windows.zip

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/NeonCharacterBuilder.jar
          target/NeonCharacterBuilder-Windows.zip
        generate_release_notes: true
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
